import { describe, it, expect } from 'vitest';
import { generateResumeText } from '../resume-export';

describe('generateResumeText', () => {
  const minimumData = {
    full_name: null,
    email: null,
    suburb: null,
    experience_text: null,
    skills: null,
    availability_text: null,
    work_rights: null,
  };

  it('returns fallback name when full_name is null', () => {
    const result = generateResumeText(minimumData);
    expect(result).toContain('Job Seeker');
  });

  it('includes email and location when provided', () => {
    const result = generateResumeText({
      ...minimumData,
      full_name: 'Jane Smith',
      email: 'jane@example.com',
      suburb: 'Fitzroy',
    });
    expect(result).toContain('Jane Smith');
    expect(result).toContain('Email: jane@example.com');
    expect(result).toContain('Location: Fitzroy, Melbourne VIC');
  });

  it('includes experience section when present', () => {
    const result = generateResumeText({
      ...minimumData,
      experience_text: 'Worked at a café for 2 years.',
    });
    expect(result).toContain('EXPERIENCE');
    expect(result).toContain('Worked at a café for 2 years.');
  });

  it('omits experience section when empty string', () => {
    const result = generateResumeText({
      ...minimumData,
      experience_text: '',
    });
    expect(result).not.toContain('EXPERIENCE');
  });

  it('includes skills as dot-separated list', () => {
    const result = generateResumeText({
      ...minimumData,
      skills: ['Customer Service', 'Barista', 'Cash Handling'],
    });
    expect(result).toContain('SKILLS');
    expect(result).toContain('Customer Service · Barista · Cash Handling');
  });

  it('omits skills section when empty array', () => {
    const result = generateResumeText({
      ...minimumData,
      skills: [],
    });
    expect(result).not.toContain('SKILLS');
  });

  it('includes availability when present', () => {
    const result = generateResumeText({
      ...minimumData,
      availability_text: 'Weekends and evenings',
    });
    expect(result).toContain('AVAILABILITY');
    expect(result).toContain('Weekends and evenings');
  });

  it('maps work_rights enum to readable label', () => {
    const result = generateResumeText({
      ...minimumData,
      work_rights: 'citizen',
    });
    expect(result).toContain('Australian Citizen / Permanent Resident');
  });

  it('maps student_visa work_rights correctly', () => {
    const result = generateResumeText({
      ...minimumData,
      work_rights: 'student_visa',
    });
    expect(result).toContain('Student Visa (with work rights)');
  });

  it('falls back to raw work_rights value when label not found', () => {
    const result = generateResumeText({
      ...minimumData,
      work_rights: 'unknown_status',
    });
    expect(result).toContain('unknown_status');
  });

  it('ends with Hi-Hired footer', () => {
    const result = generateResumeText(minimumData);
    expect(result).toContain('Generated by Hi-Hired · hihired.com.au');
  });

  it('produces a non-empty string given full profile data', () => {
    const result = generateResumeText({
      full_name: 'Alex Johnson',
      email: 'alex@example.com',
      suburb: 'Brunswick',
      experience_text: 'Retail assistant at Coles (2022–2024)\nCustomer service representative',
      skills: ['Communication', 'Teamwork', 'POS Systems'],
      availability_text: 'Full-time, immediate start',
      work_rights: 'working_holiday',
    });
    expect(result.length).toBeGreaterThan(100);
    expect(result).toContain('Alex Johnson');
    expect(result).toContain('Brunswick');
    expect(result).toContain('Customer service representative');
    expect(result).toContain('Communication · Teamwork · POS Systems');
    expect(result).toContain('Full-time, immediate start');
    expect(result).toContain('Working Holiday Visa');
  });
});
