/**
 * Resume Export — Generate a text-formatted resume from candidate profile data.
 * Uses native Share sheet on mobile, clipboard on web.
 */
import { Platform, Share, Alert } from 'react-native';

export interface ResumeData {
  full_name: string | null;
  email: string | null;
  suburb: string | null;
  experience_text: string | null;
  skills: string[] | null;
  availability_text: string | null;
  work_rights: string | null;
}

/**
 * Generate a formatted text resume from profile data.
 */
export function generateResumeText(data: ResumeData): string {
  const lines: string[] = [];
  const divider = '─'.repeat(40);

  // Header
  lines.push(data.full_name?.trim() || 'Job Seeker');
  lines.push(divider);

  // Contact
  if (data.email) {
    lines.push(`Email: ${data.email}`);
  }
  if (data.suburb) {
    lines.push(`Location: ${data.suburb}, Melbourne VIC`);
  }
  lines.push('');

  // Experience
  if (data.experience_text?.trim()) {
    lines.push('EXPERIENCE');
    lines.push(divider);
    lines.push(data.experience_text.trim());
    lines.push('');
  }

  // Skills
  if (data.skills && data.skills.length > 0) {
    lines.push('SKILLS');
    lines.push(divider);
    lines.push(data.skills.join(' · '));
    lines.push('');
  }

  // Availability
  if (data.availability_text?.trim()) {
    lines.push('AVAILABILITY');
    lines.push(divider);
    lines.push(data.availability_text.trim());
    lines.push('');
  }

  // Work Rights
  if (data.work_rights) {
    lines.push('WORK RIGHTS');
    lines.push(divider);
    const rightsLabel: Record<string, string> = {
      citizen: 'Australian Citizen / Permanent Resident',
      visa: 'Valid Work Visa',
      student_visa: 'Student Visa (with work rights)',
      working_holiday: 'Working Holiday Visa',
    };
    lines.push(rightsLabel[data.work_rights] || data.work_rights);
    lines.push('');
  }

  // Footer
  lines.push(divider);
  lines.push('Generated by Hi-Hired · hihired.com.au');

  return lines.join('\n');
}

/**
 * Share the resume via native share sheet (mobile) or copy to clipboard (web).
 */
export async function shareResume(data: ResumeData): Promise<boolean> {
  const text = generateResumeText(data);

  if (Platform.OS === 'web') {
    try {
      await navigator.clipboard.writeText(text);
      Alert.alert('Copied', 'Resume copied to clipboard.');
      return true;
    } catch {
      Alert.alert('Error', 'Could not copy to clipboard.');
      return false;
    }
  }

  try {
    const result = await Share.share(
      {
        title: `${data.full_name || 'Resume'} — Hi-Hired Resume`,
        message: text,
      },
      {
        dialogTitle: 'Share your resume',
      },
    );

    return result.action === Share.sharedAction;
  } catch {
    Alert.alert('Error', 'Could not share resume. Please try again.');
    return false;
  }
}
