
auth.token=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

defaults.org=steps-to-recovery
defaults.project=react-native-yx

defaults.url=https://sentry.io/
