{{- if .Values.serviceAccount.create -}}
---
# API ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hi-hired-backend.serviceAccountName" . }}-api
  labels:
    {{- include "hi-hired-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.annotations.apiRoleArn | quote }}
---
# Worker ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hi-hired-backend.serviceAccountName" . }}-worker
  labels:
    {{- include "hi-hired-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.annotations.workerRoleArn | quote }}
---
# Scraper ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hi-hired-backend.serviceAccountName" . }}-scraper
  labels:
    {{- include "hi-hired-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: scraper
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.annotations.scraperRoleArn | quote }}
---
# Processing Worker ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hi-hired-backend.serviceAccountName" . }}-processing
  labels:
    {{- include "hi-hired-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: processing
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.annotations.processingRoleArn | quote }}
---
# Notifications Worker ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hi-hired-backend.serviceAccountName" . }}-notifications
  labels:
    {{- include "hi-hired-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifications
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.annotations.notificationsRoleArn | quote }}
{{- end }}
