// Adzuna → Hi-Hired SQL seed generator
// Run: node scripts/adzuna-to-sql.cjs
// Needs: services/job-aggregator/.env with ADZUNA keys
const axios = require('../services/job-aggregator/node_modules/axios');
const fs = require('fs');
const path = require('path');

// Read Adzuna keys
const env = fs.readFileSync('services/job-aggregator/.env', 'utf8');
const adzunaAppId = env.match(/ADZUNA_APP_ID=(.+)/)?.[1]?.trim();
const adzunaAppKey = env.match(/ADZUNA_APP_KEY=(.+)/)?.[1]?.trim();

const SUBURB_COORDS = {
  'melbourne': [-37.8136, 144.9631], 'fitzroy': [-37.7985, 144.9786],
  'carlton': [-37.8002, 144.9708], 'brunswick': [-37.7669, 144.9632],
  'richmond': [-37.8254, 145.0012], 'south yarra': [-37.8385, 144.9941],
  'st kilda': [-37.8676, 144.9806], 'collingwood': [-37.7993, 144.9842],
  'footscray': [-37.8003, 144.8997], 'northcote': [-37.7707, 144.9993],
  'tullamarine': [-37.7063, 144.8815], 'docklands': [-37.8145, 144.9460],
  'port melbourne': [-37.8281, 144.9395], 'kensington': [-37.7934, 144.9310],
  'coburg': [-37.7439, 144.9644], 'preston': [-37.7449, 145.0065],
  'essendon': [-37.7533, 144.9151], 'werribee': [-37.9017, 144.6597],
  'frankston': [-38.1440, 145.1253], 'dandenong': [-37.9891, 145.2108],
  'brighton': [-37.9058, 144.9969], 'hawthorn': [-37.8223, 145.0354],
  'glen waverley': [-37.8779, 145.1634],
};

function normalizeSuburb(text) {
  if (!text) return 'Melbourne';
  const lower = text.toLowerCase().trim();
  for (const [key] of Object.entries(SUBURB_COORDS)) {
    if (lower.includes(key)) {
      return key.split(' ').map(w => w[0].toUpperCase() + w.slice(1)).join(' ');
    }
  }
  return 'Melbourne';
}

function isRelevant(job) {
  if (!job) return false;
  const title = (job.title || '').toLowerCase();
  const desc = (job.description || '').toLowerCase();
  const text = title + ' ' + desc;
  if (text.includes('senior ') || text.includes('director ') || text.includes('head of ')) return false;
  const shiftKeywords = ['casual', 'weekend', 'shift', 'part-time', 'part time', 'evening', 'morning', 'hourly', 'temporary', 'flexible'];
  const hasKeyword = shiftKeywords.some(k => text.includes(k));
  if (hasKeyword) return true;
  const workType = (job.contract_time || '').toLowerCase();
  return workType.includes('part') || workType === 'temp' || workType === 'contract';
}

async function main() {
  console.log('Fetching Adzuna jobs...');
  const allJobs = [];

  for (let page = 1; page <= 5; page++) {
    const resp = await axios.get(`https://api.adzuna.com/v1/api/jobs/au/search/${page}`, {
      params: {
        app_id: adzunaAppId,
        app_key: adzunaAppKey,
        results_per_page: 50,
        where: 'Melbourne',
        sort_by: 'date',
        max_days_old: 14,
      },
      timeout: 15000,
    });
    allJobs.push(...(resp.data.results || []));
    await new Promise(r => setTimeout(r, 500));
  }

  console.log(`Fetched ${allJobs.length} total jobs`);

  // Filter & transform
  const relevant = allJobs.filter(isRelevant);
  console.log(`${relevant.length} relevant jobs`);

  const transformed = relevant.slice(0, 40).map(job => {
    const title = (job.title || '').replace(/'/g, "''");
    const desc = (job.description || '').replace(/<[^>]*>/g, ' ').replace(/'/g, "''").slice(0, 300);
    const suburb = normalizeSuburb(job.location?.area?.[job.location.area.length - 1] || '');
    const sMin = job.salary_min || 0;
    const sMax = job.salary_max || 0;
    const avg = sMax > 0 ? (sMin + sMax) / 2 : sMin;
    let payDisplay, payAmount, payPeriod;
    if (avg > 50000) { payDisplay = `$${Math.round(avg / 1000)}k/yr`; payAmount = Math.round(avg); payPeriod = 'year'; }
    else if (avg > 500) { payDisplay = `$${Math.round(avg / 52)}/wk`; payAmount = Math.round(avg / 52); payPeriod = 'week'; }
    else { payDisplay = avg > 0 ? `$${Math.round(avg)}/hr` : '$30/hr'; payAmount = avg > 0 ? Math.round(avg) : 30; payPeriod = 'hour'; }
    return { title, desc, suburb, payDisplay, payAmount, payPeriod };
  });

  // Assign to employers round-robin
  const empVars = ['v_emp1_id', 'v_emp2_id', 'v_emp3_id', 'v_emp4_id'];
  const empEmails = [
    'employer.marketlane@hi-hired.demo', 'employer.pasta@hi-hired.demo',
    'employer.northside@hi-hired.demo', 'employer.littlelane@hi-hired.demo'
  ];

  const lines = [
    '-- Adzuna-imported casual/part-time jobs for Hi-Hired',
    '-- Generated by scripts/adzuna-to-sql.cjs',
    `-- ${new Date().toISOString()}`,
    '',
    'do $$',
    'declare',
    '  v_circle_id uuid;',
    '  v_emp1_id uuid; v_emp2_id uuid; v_emp3_id uuid; v_emp4_id uuid;',
    'begin',
    '  select id into v_circle_id from circles where is_default = true limit 1;',
  ];

  empEmails.forEach((email, i) => {
    lines.push(`  select id into ${empVars[i]} from profiles where email = '${email}' limit 1;`);
  });

  lines.push('');
  const vals = transformed.map((j, i) => {
    const v = empVars[i % 4];
    return `    (${v}, v_circle_id, '${j.title}', 'casual', '${j.payDisplay}', ${j.payAmount}, '${j.payPeriod}', 'Various shifts', '${j.suburb}', '${j.desc}', 'active', now() + interval '30 days')`;
  });

  lines.push('  insert into jobs (employer_id, circle_id, title, job_type, pay_display, pay_amount, pay_period, hours_text, suburb, description, status, expires_at) values');
  lines.push(vals.join(',\n') + ';');
  lines.push('  raise notice \'Done: % jobs imported\', (select count(*) from jobs);');
  lines.push('end $$;');
  lines.push('');

  const outPath = 'scripts/adzuna-import.sql';
  fs.writeFileSync(outPath, lines.join('\n'));
  console.log(`Written ${outPath} (${transformed.length} jobs)`);
}

main().catch(e => { console.error(e); process.exit(1); });
