#!/usr/bin/env bash
# Populate backend/.env from local Supabase CLI status.
# Run this after `supabase start` to keep credentials in sync.
set -euo pipefail

cd "$(dirname "$0")/.."

if ! supabase status >/dev/null 2>&1; then
  echo "Supabase is not running. Run 'supabase start' first."
  exit 1
fi

eval "$(supabase status --output env)"

cat > backend/.env <<ENVEOF
# Hi-Hired Backend — Local Development
# Auto-generated by scripts/sync-supabase-env.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
# All settings use the HH_ prefix (Pydantic Settings env_prefix).

# --- Supabase (local dev) ---
HH_SUPABASE_URL=${API_URL}
HH_SUPABASE_SERVICE_KEY=${SERVICE_ROLE_KEY}
HH_SUPABASE_JWT_SECRET=${JWT_SECRET}

# --- Redis ---
HH_REDIS_URL=redis://localhost:6379/0

# --- Celery ---
HH_CELERY_BROKER_URL=redis://localhost:6379/0
HH_CELERY_RESULT_BACKEND=redis://localhost:6379/0

# --- Qdrant ---
HH_QDRANT_URL=:memory:
HH_QDRANT_API_KEY=

# --- Observability ---
HH_OTLP_ENDPOINT=
HH_PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc

# --- API ---
HH_API_HOST=0.0.0.0
HH_API_PORT=8000
HH_CORS_ORIGINS=http://localhost:8081,http://localhost:3000,http://127.0.0.1:3000
HH_LOG_LEVEL=info

# --- Vault ---
HH_VAULT_ADDR=
HH_VAULT_TOKEN=
ENVEOF

echo "backend/.env updated from local Supabase (${API_URL})"
